version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hummek"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5dgc01790dzj"
s3_prefix = "hummek"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
